# Generated by Django 4.0.3 on 2022-03-12 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('did not apply', 'Не задано'), ('drinks', 'Лимонады'), ('cakes', 'Торты')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product_pics', verbose_name='Картинка')),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
